phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - node --verion
  pre_build:
    commands:
       - npm install
  build:
    commands:
     - node init
    paths:
      - "node_modules/**/*"