version: 0.2

env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get update
      - apt-get install -y jq
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - apt-get update
      - apt-get -y install maven 
      - SNYK_TOKEN=b5511ecc-7468-4383-8590-f3c9d291fcc2
      - export SNYK_TOKEN
      - mvn snyk:test -fn 
      - apt-get update
      - apt-get -y install wget
      - apt-get -y install default-jdk
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
      - mkdir zap
      - tar -xvf ZAP_2.11.1_Linux.tar.gz
      - cd ZAP_2.11.1
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html  
  pre_build:
    commands:
      - sonar-scanner -Dsonar.organization=sonar88 -Dsonar.projectKey=sonarcloud88 -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$LOGIN
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=SITEWEB > analysis.json
      - cat analysis.json
  build:
    commands:
      - echo Building Project
      - echo Finished Building
    paths:
      - "node_modules/**/*"
  artifacts:
    files:
      - zap_report.html
