version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - node --version
  build:
    commands:
      - npm init
  post_build:
    commands:
      - echo Build completed on `date`
