version: '3'


services:
  #Aplicaçao criar dockerhub e fazer o build
  #web_aplication:
  #  image: your_application_image:tag
  #  ports:
  #    - "80:80"

  jenkins:
    image: brunosantos88/jenkinserver:31
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_data:/var/jenkins_home
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: "host"
 
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
     - '9093:9093'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    network_mode: "host"


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    network_mode: "host"

volumes:
  grafana-data:
  jenkins_data: