version: '3'


services:
  #Aplicaçao criar dockerhub e fazer o build
  #web_aplication:
  #  image: your_application_image:tag
  #  ports:
  #    - "80:80"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_data:/var/jenkins_home
    network_mode: "host"

volumes:
 jenkins_data: