global:
  scrape_interval: 5s
  evaluation_interval: 10s

  
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093
       
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'web_app'
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:80"]
  - job_name: 'jenkins'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:8080"]
    
  
  
 
