name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this branch according to your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: brunosantos88/amazonlinuxagent
        # Add more tags or customize as needed

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
